use_frameworks!

platform :ios, '11.0'

target 'TMKit_Example' do
  pod 'TMKit-iOS', :path => '../'

  target 'TMKit_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
      
      config.build_settings['WARNING_CFLAGS'] ||= ["-w"]
    end
  end
end
